"""SQLAlchemy models for the stock agent database."""
from datetime import datetime
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Text, ForeignKey, Boolean, create_engine
)
from sqlalchemy.orm import declarative_base, relationship, sessionmaker
from sqlalchemy.pool import StaticPool

from backend.config import DB_PATH

Base = declarative_base()


class MarketEvent(Base):
    """Detected market-moving events classified from news."""
    __tablename__ = "market_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    news_id = Column(Integer, ForeignKey("news.id"), nullable=False, index=True)
    event_type = Column(String(32), nullable=False)       # govt_contract, earnings_beat, etc.
    impact = Column(String(8), nullable=False)             # high, medium, low
    affected_tickers = Column(Text)                        # comma-separated NSE symbols
    affected_sectors = Column(Text)                        # comma-separated sectors
    sentiment_hint = Column(String(16))                    # positive, negative, neutral
    keywords = Column(Text)                                # matched keywords
    title = Column(String(512))
    source = Column(String(128))
    published_at = Column(DateTime)
    created_at = Column(DateTime, default=datetime.utcnow)


class Prediction(Base):
    """Predictive signals: forward-looking buy/sell/watch recommendations."""
    __tablename__ = "predictions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(16), nullable=False, index=True)
    news_id = Column(Integer, ForeignKey("news.id"), nullable=True)
    event_type = Column(String(32))
    predicted_direction = Column(String(8))               # up, down, neutral
    predicted_pct_low = Column(Float)                     # e.g. 2.0 = +2%
    predicted_pct_high = Column(Float)                    # e.g. 6.0 = +6%
    confidence = Column(Float)                            # 0-100
    action = Column(String(24))                           # BUY NOW, BUY AT OPEN, SELL, WATCH, AVOID
    timing_window = Column(Text)                          # plain English timing description
    entry_time = Column(String(64))                       # e.g. "9:15–9:45 AM IST"
    stop_loss_pct = Column(Float)                         # % below entry
    reasoning = Column(Text)                              # plain English chain of logic
    sector_impact = Column(Text)                          # comma-separated sectors
    affected_tickers = Column(Text)                       # comma-separated related tickers
    actual_outcome = Column(Float)                        # filled later for backtesting
    created_at = Column(DateTime, default=datetime.utcnow, index=True)


class News(Base):
    """Business news articles from RSS feeds."""
    __tablename__ = "news"

    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String(512), nullable=False)
    link = Column(Text, nullable=False)
    source = Column(String(128), nullable=False)
    category = Column(String(32))  # market, political, geopolitical, tech, sports
    published_at = Column(DateTime, nullable=False)
    summary = Column(Text)
    sentiment_score = Column(Float)  # -1 to 1 from VADER
    tickers = Column(Text)  # Comma-separated tickers mentioned
    created_at = Column(DateTime, default=datetime.utcnow)


class StockPrice(Base):
    """OHLCV stock price data."""
    __tablename__ = "stock_prices"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(16), nullable=False, index=True)
    date = Column(DateTime, nullable=False, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Integer)
    created_at = Column(DateTime, default=datetime.utcnow)


class Watchlist(Base):
    """User's stock watchlist."""
    __tablename__ = "watchlist"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(16), nullable=False, unique=True)
    added_at = Column(DateTime, default=datetime.utcnow)


class Holding(Base):
    """User's stock holdings (stocks they bought)."""
    __tablename__ = "holdings"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(20), nullable=False)
    quantity = Column(Integer, nullable=False)
    buy_price = Column(Float, nullable=False)
    buy_date = Column(DateTime, default=datetime.utcnow)
    notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)


class Signal(Base):
    """Buy/sell/hold signals generated by the rule engine."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(16), nullable=False, index=True)
    signal = Column(String(8), nullable=False)  # buy, sell, hold
    confidence = Column(Float)  # 0-100
    reason = Column(Text)
    rsi = Column(Float)
    sentiment = Column(Float)
    macd_signal = Column(String(16))
    created_at = Column(DateTime, default=datetime.utcnow)


# Engine and session
engine = create_engine(
    f"sqlite:///{DB_PATH}",
    connect_args={"check_same_thread": False},
    poolclass=StaticPool,
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def get_db():
    """Dependency for FastAPI to get DB session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
